# Generated by Django 3.2.3 on 2021-11-29 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employess',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField(max_length=100, unique=True)),
                ('employee_id', models.IntegerField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100)),
            name='Inventorymodel',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ordermodel',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=40)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='mainapp.inventorymodel')),
            ],
        ),
    ]
